services:
  action_stream_postgres:
    image: postgres:17-alpine
    container_name: auction_stream_postgres
    restart: always
    command: [ "postgres", "-c", "log_min_duration_statement=1000", "-c", "log_destination=stderr" ]
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      - auction-stream-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  kafka:
    image: confluentinc/cp-kafka:7.8.0
    container_name: kafka
    hostname: kafka
    ports:
      - 9092:9092 # Kafka client port
      - 9093:9093 # Internal Raft communication port
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_LISTENERS: 'INTERNAL://kafka:9094,CONTROLLER://kafka:9093,EXTERNAL://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:9094,EXTERNAL://localhost:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      CLUSTER_ID: '2odeySxpSGyzURgw79CUKQ'
    volumes:
      - kafka-data:/var/lib/kafka/data
  akhq:
      image: tchiotludo/akhq:0.25.1
      container_name: akhq
      depends_on:
        - kafka
      ports:
        - 9090:8080
      environment:
        AKHQ_CONFIGURATION: |
          akhq:
            connections:
              kafka:
                properties:
                  bootstrap.servers: kafka:9094

volumes:
  auction-stream-data:
  kafka-data: